#!/usr/bin/env python3
"""Figure 1, lower-left panel: the routing weights DAGFormer-300M learned (predictor + local correction, mean over tokens).

Reads experiments/topology/300m_corrected_topology.npz (scripts/topology_analysis.py: 128 held-out windows of
1024 tokens of the model's own corpus) and writes figures/method_alpha.tex, TikZ cells that figures/method.tex
\\input's inside its tikzpicture.

Per stream s in {q, k, v, r} and target layer l = 2..12 (npz key L{l-1}; layer 1 reads only X_0 and is not routed),
the cell (l, j) is the share of the mean effective |alpha| (predictor + local correction, as in Appendix topology) that layer l's stream puts on source X_j, j < l:
  q, k, v: |mean over tokens of alpha_{s,h,j}| averaged over the 16 heads, then normalised over j;
  r:       |mean over tokens of alpha_{r,j}|, normalised over j.
The outlined cell of each row is X_{l-1}, the only source with nonzero weight at initialization (= dense OLMo-2).
Run from paper/:  python figures/gen_method_alpha.py
"""
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
NPZ = HERE.parent.parent / "experiments" / "topology" / "300m_corrected_topology.npz"
OUT = HERE / "method_alpha.tex"
L = 12                       # layers of the 300M model
CELL = 0.125                 # cm per cell
X0 = {"q": 1.3, "k": 2.97, "v": 4.64, "r": 6.31}   # left edge of each grid (method.tex coordinates)
YTOP = 4.30                  # top edge of the grids
COLOR = {"q": "cQ", "k": "cK", "v": "cV", "r": "cR"}
SAT = 0.45                   # share mapped to full colour
GAMMA = 0.6                  # < 1 lifts small shares so the skip pattern stays visible


def shares(z, s):
    rows = {}
    for l in range(2, L + 1):
        a = z[f"L{l-1}_{s}_eff_mean"]
        m = np.abs(a).mean(0) if a.ndim == 2 else np.abs(a)
        rows[l] = m / m.sum()
    return rows


def main():
    z = np.load(NPZ)
    out = ["% generated by figures/gen_method_alpha.py from experiments/topology/300m_corrected_topology.npz -- do not edit",
           "% share of the mean effective |alpha| (predictor + correction) per (target layer l = 2..12, source X_j), DAGFormer-300M"]
    summary = []
    for s, x0 in X0.items():
        sh = shares(z, s)
        for l, row in sh.items():
            y = YTOP - (l - 2) * CELL
            for j, v in enumerate(row):
                pct = int(round(100 * min(1.0, (v / SAT) ** GAMMA)))
                out.append(f"\\fill[{COLOR[s]}!{pct}!white] ({x0 + j * CELL:.3f},{y:.3f}) rectangle ++({CELL},-{CELL});")
            # previous-layer source: the identity initialization
            out.append(f"\\draw[black!80, line width=0.35pt] ({x0 + (l - 1) * CELL:.3f},{y:.3f}) rectangle ++({CELL},-{CELL});")
        # light grid over the lower triangle and the frame
        for l in range(2, L + 1):
            y = YTOP - (l - 2) * CELL
            out.append(f"\\draw[black!18, line width=0.15pt] ({x0:.3f},{y:.3f}) rectangle ++({l * CELL:.3f},-{CELL});")
        out.append(f"\\draw[black!55, line width=0.4pt] ({x0:.3f},{YTOP:.3f}) rectangle ++({L * CELL:.3f},-{(L - 1) * CELL:.3f});")
        prev = np.mean([sh[l][l - 1] for l in sh])
        emb = np.mean([sh[l][0] for l in sh])
        summary.append(f"{s}: previous layer {prev:.2f}, embedding X_0 {emb:.2f} (mean share over layers 2-12)")
    OUT.write_text("\n".join(out) + "\n")
    print(f"wrote {OUT}")
    print("\n".join(summary))


if __name__ == "__main__":
    main()
