"""Generate paper/table_downstream.tex (Table 2): the 12 multiple-choice tasks and GSM8K for the base and instruction-tuned models,
their mean over the 13 tasks, and the judged chat win rates after instruction tuning.

Sources: experiments/results/lmeval/sft/SUMMARY_300m.md and SUMMARY_1b.md (base rows; metric per task as in
SUMMARY_locality.md: arc_challenge/arc_easy/mathqa/openbookqa/hellaswag/piqa = acc_norm, the other six = acc,
gsm8k = 3-shot exact match, flexible extract, first 200 problems) and experiments/chat_eval/RESULTS.md numbers as
printed in the paper (win rates, dagger = 95% bootstrap interval excludes 0.5).
    python paper/make_table_downstream.py
"""
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
L = os.path.join(REPO, "experiments/results/lmeval/sft")
TASKS = [("arc_easy", "ARC-e"), ("arc_challenge", "ARC-c"), ("hellaswag", "HSwag"), ("piqa", "PIQA"),
         ("winogrande", "WinoG"), ("openbookqa", "OBQA"), ("sciq", "SciQ"), ("boolq", "BoolQ"),
         ("lambada_openai", "LAMB"), ("commonsense_qa", "CSQA"), ("social_iqa", "SIQA"), ("mathqa", "MathQA"),
         ("gsm8k", "GSM8K")]


def rows(path):
    hdr, out = None, []
    for line in open(path):
        if not line.startswith("|") or set(line.strip()) <= {"|", "-", " "}:
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if hdr is None and cells[0] == "model":
            hdr = cells
            continue
        if hdr and len(cells) == len(hdr):
            out.append(dict(zip(hdr, cells)))
        elif hdr and cells[0] == "model":
            break
    return out


r300 = rows(os.path.join(L, "SUMMARY_300m.md"))
r1b = rows(os.path.join(L, "SUMMARY_1b.md"))
pick = lambda rs, model, stage, tokens=None: next(r for r in rs if r["model"] == model and r["stage"].startswith(stage)
                                                  and (tokens is None or r.get("tokens") == tokens))
STAGES = [("base", "base"), ("+Alpaca", "+Alpaca"), ("+SmolTalk", "+SmolTalk")]
CHAT = {("300M", "+Alpaca"): ".57", ("300M", "+SmolTalk"): ".69$^\\dagger$", ("1B, 5B", "+Alpaca"): ".58$^\\dagger$",
        ("1B, 5B", "+SmolTalk"): ".59$^\\dagger$", ("1B, 10B", "+Alpaca"): ".56", ("1B, 10B", "+SmolTalk"): ".64$^\\dagger$"}
# main table: 300M and the 1B models at 10B tokens (labelled "1B"); appendix table: the 1B models at 5B tokens
OUTPUTS = [("table_downstream.tex", [("300M", r300, "dense", "four-way corrected", None),
                                     ("1B", r1b, "dense", "DAGFormer four-way corrected", "10B")]),
           ("table_downstream_1b5b.tex", [("1B, 5B tok.", r1b, "dense", "DAGFormer four-way corrected", "5B")])]


def vals(r):
    v = [100 * float(r[k]) for k, _ in TASKS]
    return v + [sum(v) / len(v)]


for outname, SIZES in OUTPUTS:
  lines, summary = [], []
  for size, rs, dn, gn, tok in SIZES:
      for si, (stage, key) in enumerate(STAGES):
          d, g = pick(rs, dn, key, tok), pick(rs, gn, key, tok)
          vd, vg = vals(d), vals(g)
          fd = [f"{x:.1f}" for x in vd]; fg = [f"{x:.1f}" for x in vg]
          for i in range(len(vd)):
              if fd[i] == fg[i]:
                  fd[i], fg[i] = f"\\textbf{{{fd[i]}}}", f"\\textbf{{{fg[i]}}}"
              elif vg[i] > vd[i]:
                  fg[i] = f"\\textbf{{{fg[i]}}}"
              else:
                  fd[i] = f"\\textbf{{{fd[i]}}}"
          summary.append((size, stage, sum(vg[i] > vd[i] for i in range(13)), sum(f"{vg[i]:.1f}" == f"{vd[i]:.1f}" for i in range(13)), vd[-1], vg[-1]))
          lab = size if si == 0 else ""
          lines.append(f"{lab} & {stage} & dense & " + " & ".join(fd) + " \\\\")
          lines.append(f" & & \\dagf{{}} & " + " & ".join(fg) + " \\\\")
          lines.append("\\addlinespace[1pt]" if si < 2 else "\\midrule")
  lines.pop()
  head = " & ".join(h for _, h in TASKS)
  tex = ("% generated by paper/make_table_downstream.py from experiments/results/lmeval/sft/SUMMARY_{300m,1b}.md -- do not edit\n"
         "\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}}lll " + "r" * 13 + " r}\n\\toprule\n"
         " & & & \\multicolumn{14}{c}{accuracy (\\%) $\\uparrow$} \\\\\n"
         "\\cmidrule(lr){4-17}\n"
         f"size & stage & model & {head} & \\textbf{{Mean}} \\\\\n\\midrule\n" + "\n".join(lines) +
         "\n\\bottomrule\n\\end{tabular*}\n")
  open(os.path.join(os.path.dirname(os.path.abspath(__file__)), outname), "w").write(tex)
  for w in summary:
      print(f"{w[0]:8s} {w[1]:10s}: DAGFormer ahead on {w[2]:2d} of 13 (ties {w[3]}); mean {w[4]:.1f} -> {w[5]:.1f}")
