"""Generate the pruning tables.

table_pruning.tex        (Table 4, body): every Table 1 model pruned from its Table 1 checkpoint (matched corpus: 75M/150M on
                          the 12B' slice, 300M on the 21B corpus). Per size: MathInstruct held-out NLL of the unpruned finetune
                          (0%) and the loss increase relative to it with 50% and 70% of heads and MLP channels removed.
table_pruning_full.tex   (appendix): the same runs at 0/30/50/70% and the frozen-router controls at 50%.
table_pruning_shared.tex (appendix): the earlier shared-slice pairs (dense vs DAGFormer, 75M-300M) and the 150M comparison with
                          MUDDFormer on a common corpus (experiments/pruning/results/prune_summary.md,
                          experiments/coherence/results/exp3/prune_summary.md).
Source of the matched runs: experiments/pruning/results/matched/summary.json (scripts/collect_prune_matched.py).
Missing runs print as \\pend{}.
    python paper/make_table_pruning.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
M = json.load(open(os.path.join(REPO, "experiments/pruning/results/matched/summary.json")))
FAMS = [("dense", "dense"), ("denseformer", "DenseFormer"), ("hc_paper", "hyper-conn."), ("mhc", "mHC"),
        ("muddformer", "MUDDFormer"), ("dagformer", "\\dagf{}")]
SIZES = [("75m", "75M"), ("150m", "150M"), ("300m", "300M")]
PEND = "\\pend{}"


def nll(size, fam, suf):
    r = M.get(f"{size}/{fam}{suf}")
    return r["final_domain_nll"] if r else None


def inc(size, fam, k):
    a, b = nll(size, fam, "_s0"), nll(size, fam, f"_s{k}")
    return 100 * (b / a - 1) if (a and b) else None


def cells(vals, fmt, best=min):
    """format a column; bold the best of the filled cells (ties at printed precision all bold)"""
    txt = [fmt.format(v) if v is not None else PEND for v in vals]
    filled = [fmt.format(v) for v in vals if v is not None]
    if len(filled) >= 2:
        b = fmt.format(best(v for v in vals if v is not None))
        txt = [f"\\textbf{{{t}}}" if t == b else t for t in txt]
    return txt


# ---- body table: rows = families, column groups = sizes (NLL 0%, +% at 50, +% at 70)
cols = {}
for s, _ in SIZES:
    cols[(s, 0)] = cells([nll(s, f, "_s0") for f, _ in FAMS], "{:.3f}")
    cols[(s, 50)] = cells([inc(s, f, 50) for f, _ in FAMS], "{:.1f}")
    cols[(s, 70)] = cells([inc(s, f, 70) for f, _ in FAMS], "{:.1f}")
lines = []
for i, (_, lab) in enumerate(FAMS):
    lines.append(f"{lab} & " + " & ".join(f"{cols[(s, 0)][i]} & {cols[(s, 50)][i]} & {cols[(s, 70)][i]}" for s, _ in SIZES) + " \\\\")
hdr = "% generated by paper/make_table_pruning.py from experiments/pruning/results/matched/summary.json -- do not edit\n"
open(os.path.join(HERE, "table_pruning.tex"), "w").write(
    hdr + "\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}}l rrr rrr rrr}\n\\toprule\n"
    " & \\multicolumn{3}{c}{75M} & \\multicolumn{3}{c}{150M} & \\multicolumn{3}{c}{300M} \\\\\n"
    "\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}\\cmidrule(lr){8-10}\n"
    " & NLL $\\downarrow$ & \\multicolumn{2}{c}{increase (\\%) $\\downarrow$} & NLL $\\downarrow$ & \\multicolumn{2}{c}{increase (\\%) $\\downarrow$}"
    " & NLL $\\downarrow$ & \\multicolumn{2}{c}{increase (\\%) $\\downarrow$} \\\\\n"
    "model & 0\\% & 50\\% & 70\\% & 0\\% & 50\\% & 70\\% & 0\\% & 50\\% & 70\\% \\\\\n\\midrule\n"
    + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular*}\n")

# ---- appendix: full matched grid
lines = []
for bi, (s, slab) in enumerate(SIZES):
    grid = {f: [nll(s, f, f"_s{k}") for k in (0, 30, 50, 70)] for f, _ in FAMS}
    colv = list(zip(*grid.values()))
    best = [min((v for v in c if v is not None), default=None) for c in colv]
    for mi, (f, lab) in enumerate(FAMS):
        c = []
        for k, v in enumerate(grid[f]):
            t = f"{v:.3f}" if v is not None else PEND
            c.append(f"\\textbf{{{t}}}" if v is not None and best[k] is not None and t == f"{best[k]:.3f}" else t)
        fa = nll(s, f, "_s50_frozenall")
        fp = nll(s, f, "_s50_frozenpred")
        fa_t = "--" if f == "dense" else (f"{fa:.3f}" if fa is not None else PEND)
        fp_t = (f"{fp:.3f}" if fp is not None else PEND) if f == "dagformer" else "--"
        lines.append(f"{slab if mi == 0 else ''} & {lab} & " + " & ".join(c) + f" & {fa_t} & {fp_t} \\\\")
    if bi < len(SIZES) - 1:
        lines.append("\\addlinespace[2pt]")
open(os.path.join(HERE, "table_pruning_full.tex"), "w").write(
    hdr + "\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}}ll rrrr rr}\n\\toprule\n"
    " & & \\multicolumn{4}{c}{held-out NLL $\\downarrow$ at sparsity} & \\multicolumn{2}{c}{NLL at 50\\%, routers frozen} \\\\\n"
    "\\cmidrule(lr){3-6}\\cmidrule(lr){7-8}\n"
    "size & model & 0\\% & 30\\% & 50\\% & 70\\% & all routers & predictor only \\\\\n\\midrule\n"
    + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular*}\n")


# ---- appendix: the earlier shared-slice tables (unchanged content of the previous Table 4)
def table(path):
    rows, hdr_ = {}, None
    for line in open(path):
        if not line.startswith("|") or set(line.strip()) <= {"|", "-", " "}:
            continue
        cells_ = [c.strip() for c in line.strip().strip("|").split("|")]
        if cells_[0] == "run":
            hdr_ = cells_
            continue
        if hdr_ and cells_[0] != "size" and len(cells_) == len(hdr_):
            rows[cells_[0]] = dict(zip(hdr_, cells_))
        elif cells_[0] == "size":
            break
    return rows


A = table(os.path.join(REPO, "experiments/pruning/results/prune_summary.md"))
B = table(os.path.join(REPO, "experiments/coherence/results/exp3/prune_summary.md"))
fnll = lambda t, run: float(t[run]["NLL final"]) if run in t else None
BLOCKS = [("75M", A, [("dense", "75m_baseline"), ("\\dagf{}", "75m_dagformer")], "frozenpred"),
          ("150M", A, [("dense", "150m_baseline"), ("\\dagf{}", "150m_dagformer")], "frozenpred"),
          ("300M", A, [("dense", "300m_baseline"), ("\\dagf{}", "300m_dagformer")], "frozenpred"),
          ("150M$^\\ast$", B, [("dense", "150m_baselinest"), ("MUDDFormer", "150m_muddformer"), ("\\dagf{}", "150m_dagformerst")], "frozenrouter")]
lines = []
for bi, (size, t, models, frozen) in enumerate(BLOCKS):
    grid = {name: [fnll(t, f"{pre}_math_s{k}") for k in (0, 30, 50, 70)] + [fnll(t, f"{pre}_math_s50_{frozen}")]
            for name, pre in models}
    best = [min(v[i] for v in grid.values() if v[i] is not None) for i in range(4)]
    for mi, (name, _) in enumerate(models):
        c = []
        for i, x in enumerate(grid[name]):
            if x is None:
                c.append("--")
            else:
                cc = f"{x:.3f}"
                c.append(f"\\textbf{{{cc}}}" if i < 4 and cc == f"{best[i]:.3f}" else cc)
        rel = [100 * (grid[name][i] / grid[name][0] - 1) for i in (2, 3)]
        lines.append(f"{size if mi == 0 else ''} & {name} & " + " & ".join(c[:4]) + f" & {rel[0]:.1f} & {rel[1]:.1f} & {c[4]} \\\\")
    if bi < len(BLOCKS) - 1:
        lines.append("\\addlinespace[2pt]")
open(os.path.join(HERE, "table_pruning_shared.tex"), "w").write(
    "% generated by paper/make_table_pruning.py from experiments/pruning/results/prune_summary.md and "
    "experiments/coherence/results/exp3/prune_summary.md -- do not edit\n"
    "\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}}ll rrrr rr r}\n\\toprule\n"
    " & & \\multicolumn{4}{c}{held-out NLL $\\downarrow$} & \\multicolumn{2}{c}{increase (\\%)} & frozen \\\\\n"
    "\\cmidrule(lr){3-6}\\cmidrule(lr){7-8}\\cmidrule(lr){9-9}\n"
    "size & model & 0\\% & 30\\% & 50\\% & 70\\% & at 50\\% & at 70\\% & NLL at 50\\% \\\\\n\\midrule\n" + "\n".join(lines) +
    "\n\\bottomrule\n\\end{tabular*}\n")
print(open(os.path.join(HERE, "table_pruning.tex")).read())
