"""Generate the measured-cost tables from experiments/scaling/inference_cost.json (scripts/inference_bench.py):
table_cost_rows.tex   -- the inference block of Table 1 (time per token relative to dense, prefill, every family and size)
table_traincost.tex   -- Appendix A: training throughput (forward + backward) relative to dense, and dense tokens/s.
    python paper/make_cost_tables.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
D = json.load(open(os.path.join(HERE, "..", "experiments/scaling/inference_cost.json")))
FAMS = ["dense", "denseformer", "hc_paper", "mhc", "muddformer", "dagformer"]
SIZES = [("75m", "75M"), ("150m", "150M"), ("300m", "300M"), ("1b", "1B")]
R = {(r["size"], r["family"]): r for r in D["runs"] if "error" not in r}


def ratio(size, fam, key):
    return R[(size, "dense")][key] / R[(size, fam)][key]


rows, trows = [], []
for s, lab in SIZES:
    rows.append(f"{lab} & " + " & ".join(f"{ratio(s, f, 'infer_tok_per_s'):.2f}" for f in FAMS) + " & \\\\")
    trows.append(f"{lab} & {R[(s, 'dense')]['train_tok_per_s'] / 1e3:.1f}K & "
                 + " & ".join(f"{ratio(s, f, 'train_tok_per_s'):.2f}" for f in FAMS[1:])
                 + f" & {R[(s, 'dense')]['infer_tok_per_s'] / 1e3:.0f}K \\\\")
hdr = f"% generated by paper/make_cost_tables.py from experiments/scaling/inference_cost.json ({D['gpu']}) -- do not edit\n"
# the \bottomrule lives in this file: a rule right after \input inside a tabular is a misplaced \noalign
open(os.path.join(HERE, "table_cost_rows.tex"), "w").write(hdr + "\n".join(rows) + "\n\\bottomrule\n")
open(os.path.join(HERE, "table_traincost.tex"), "w").write(
    hdr + "\\begin{tabular}{l r rrrrr r}\n\\toprule\n"
    " & \\multicolumn{6}{c}{training: time per token relative to dense $\\downarrow$} & inference \\\\\n"
    "\\cmidrule(lr){2-7}\\cmidrule(lr){8-8}\n"
    "size & dense (tok/s) & DenseFormer & hyper-conn. & mHC & MUDDFormer & \\dagf{} & dense (tok/s) \\\\\n\\midrule\n"
    + "\n".join(trows) + "\n\\bottomrule\n\\end{tabular}\n")
for f in FAMS[1:]:
    inf = [ratio(s, f, "infer_tok_per_s") for s, _ in SIZES]
    tr = [ratio(s, f, "train_tok_per_s") for s, _ in SIZES]
    print(f"{f:12s} infer " + " ".join(f"{x:.2f}" for x in inf) + "   train " + " ".join(f"{x:.2f}" for x in tr))
print("peak inference memory (GB):", {f"{s}/{f}": round(R[(s, f)]["infer_peak_gb"], 1) for s, _ in SIZES for f in ("dense", "dagformer")})
